blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.posts_list, name="posts_list"),
    path('tag/<slug:tag_slug>/', views.posts_list, name='post_list_by_tag'),
    # path("", views.PostListView.as_view(), name="posts_list"),
    # path('<int:id>/', views.post_detail, name='post_detail'),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", views.post_detail, name="post_detail"),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),

]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    path("api/", include("blog_api.urls")),
    path("api-auth/", include("rest_framework.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/before_bootstrap/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
<div id="content">

    {% if messages %}
    {% for message in messages %}

    {{ message.tags }} {{ message }}

    {% endfor %}

    {% endif %}

    {% block content %} {% endblock %}

</div>

<div id="sidebar">

    <a href="{% url 'blog:post_search' %}">Поиск</a>

    {% if user.is_authenticated  %}
    <a class="admin" href="/admin">Админ</a>
    {% endif %}

    <h2>
        <a href="{% url 'blog:posts_list' %}">
            Блог
        </a>
    </h2>

    <p>Про Django и другое</p>
    <p>Всего опубликовано {% total_posts %} постов</p>

        <hr>
        {% if user.is_authenticated %}
        Привет, {{ user.username }}!
        <p><a href="{% url 'users-profile' %}">Мой профиль</a></p>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <a href="#" onclick="parentNode.submit();">Выйти</a>
        </form>
        {% else %}
        <p>Вы не авторизованы</p>
        <p><a href="{% url 'login' %}">Войти</a></p>
        <p><a href="{% url 'password_reset' %}">Забыли пароль?</a></p>
        {% endif %}
        <hr>

     <h3>Последние посты</h3>
    {% show_latest_posts 3 %}
    <h3>Популярные посты</h3>
      {% get_most_commented_posts as most_commented_posts %}
      <ul>
         {% for post in most_commented_posts %}
         <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
         </li>
         {% endfor %}
      </ul>

</div>

</body>
</html>

templates/before_bootstrap/change_password.html
{% extends "blog/base.html" %}
{% block content %}
    <h3>Сменить пароль</h3>
    {% if form.errors %}
        <div role="alert">
            <div id="form_errors">
                {% for key, value in form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <form method="POST">
        {% csrf_token %}

        <label>Старый пароль</label>
        <input type="password" name="old_password" autocomplete="new-password" required id="id_old_password"
               placeholder="Enter Old Password"/>
        <br>


        <label>Новый пароль</label>
        <input type="password" name="new_password1" autocomplete="new-password"
               required id="id_new_password1"
               placeholder="Enter New Password"/>

        <br>

        <label for="id_new_password2">Повторить новый пароль</label>
        <input type="password" name="new_password2" autocomplete="new-password"
               required id="id_new_password2" placeholder="Confirm New Password"/>

        <br>
        <button type="submit" id="reset">Обновить пароль</button>
    </form>
{% endblock content %}

templates/before_bootstrap/comment_form.html
<h2>Добавить новый комментарий</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Отправить"></p>
</form>

templates/before_bootstrap/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Опубликовано {{ post.publish }}. Автор: {{ post.author }}
    </p>
    <!--{{ post.body|linebreaks }}-->
         {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Поделиться постом
        </a>
    </p>

    <h2>Похожие посты</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Нет похожих постов
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий № {{ forloop.counter }} от {{ comment.name }}
                ( {{ comment.created }} )
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Нет комментариев.</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

templates/before_bootstrap/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}

    <h1>Новости</h1>

    {% if tag %}
        <h2>Посты с тэгом: "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href=" {{ post.get_absolute_url }} "> {{ post.title }}</a>
        </h2>

        <p class="tags">
            Тэги:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>

        <p class="date">
    <!--<p class="tags">Тэги: {{ post.tags.all|join:", " }}</p>-->
            Опубликовано {{ post.publish }}. Автор: {{ post.author }}
        </p>
        <!--{{ post.body|truncatewords:30|linebreaks }}-->
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}

    {% include "pagination.html" with page=posts %}  <!-- на основе функций-->
<!--{% include "pagination.html" with page=page_obj %} &lt;!&ndash;на основе классов&ndash;&gt;-->


{% endblock %}

templates/before_bootstrap/login.html
{% extends "blog/base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
    <h2> Login </h2>
    <a href="{% url 'social:begin' 'github' %}">Log In with GitHub</a>
    <br>
    <a href="{% url 'social:begin' 'google-oauth2' %}">Log In with Google</a>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Войти"></p>
        <p><a href="{% url 'password_reset' %}">Сбросить пароль</a></p>
        <p><a href="{% url 'signup' %}">Зарегистрироваться</a></p>
    </form>
{% endblock %}

templates/before_bootstrap/pagination.html
<div class="pagination">
    <span class="step-links">
     {% if page.has_previous %}     <!--если есть предыдущая страница то показываем ее кнопку-->
       <a href="?page={{ page.previous_page_number }}">Пред.</a>   <!--возвращает номер предыдущей страницы-->
        {% endif %}
        <span class="current">
           Стр. {{ page.number }} из {{ page.paginator.num_pages }}.
        </span>
       {% if page.has_next %}   <!--если есть следующая страница то показываем ее кнопку-->
          <a href="?page={{ page.next_page_number }}">След.</a>   <!--возвращает номер следуюущей страницы-->
        {% endif %}
    </span>
</div>

templates/before_bootstrap/profile.html
{% extends "blog/base.html" %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
    <div>
        <img src="{{ user.profile.avatar.url }} " style="cursor: pointer;"/>
    </div>
    {% if user_form.errors %}
        <div role="alert">
            <div>
                {% for key, value in user_form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="form-content">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <div>
                    <div>
                        <label>Имя пользователя:</label>
                        {{ user_form.username }}
                        <hr>
                        <label>Email:</label>
                        {{ user_form.email }}
                    </div>
                    <hr>
                    <div>
                        <a href="{% url 'password_change' %}">Изменить пароль</a>
                        <hr>
                        <label>Изменить аватар:</label>
                        {{ profile_form.avatar }}
                    </div>
                    <hr>
                    <label>Bio:</label> {{ profile_form.bio }}
                </div>
            </div>
            <br><br>
            <button type="submit">Сохранить изменения</button>
            <button type="reset">Сбросить</button>
        </form>
    </div>
{% endblock content %}

templates/before_bootstrap/search.html
{% extends "blog/base.html" %} {% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %} {% if query %}
    <h1>
        Посты, содержащие "{{ query }}"
    </h1>
    <h3>
        {% with results.count as total_results %}
            Found {{ total_results }} resultat{{ total_results|pluralize }} {% endwith %}
    </h3>
    {% for post in results %}
        <h4>
            <a href="{{ post.get_absolute_url }}"> {{ post.title }}
            </a>
        </h4>
        {{ post.body|markdown|truncatewords_html:12 }} {% empty %}
        <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url 'blog:post_search' %}">Искать снова</a></p> {% else %}
    <h1>
        Поиск постов
    </h1>
    <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Найти">
    </form>
{% endif %} {% endblock %}

templates/before_bootstrap/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Отправка письма</h1>
        <p>
            Ссылка на пост "{{ post.title }}" была успешно отправлена
            на {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Отправить "{{ post.title }}" по почте</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить">
        </form>
    {% endif %}
{% endblock %}

templates/before_bootstrap/signup.html
{% extends "blog/base.html" %}
{% block title %} Sign Up {% endblock %}
{% block content %}
    <h2> Зарегистрироваться </h2>
    {% if form.errors %}
        <div style="display: table; margin: 0 auto; text-align: left;">
            {% for key, value in form.errors.items %}
                <strong>{{ value }}</strong>
            {% endfor %}
        </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <p>Username: {{ form.username }}</p>
        <p>Email: {{ form.email }}</p>
        <p>First Name: {{ form.first_name }}</p>
        <p>Last Name: {{ form.last_name }}</p>
        <p>Password: {{ form.password1 }}</p>
        <p>Confirm Password: {{ form.password2 }}</p>
        <button type="submit">Зарегистрироваться</button>
    </form>
    <br>
    <a href="{% url 'login' %}">Уже зарегистрированы? Перейти к авторизации.</a>
{% endblock %}